### ISSUE TITLE
Help needed with randomly selecting String

### ISSUE THREAD

**Issue by PotatoCurry** [PotatoCurry/Yibot#1]
I don't know why this won't work; in my head it makes sense.
```
public static String ChooseRandom(ArrayList<String> arr) 
    return arr.get(MethodsDL.Random(0, arr.size() - 1));
}
```
Choosing a random String from an `ArrayList` is essential to this project, so any help would be appreciated!

Edit: It doesn't seem to be an issue with this code snippet, see below.

**Comment by theDyingday** [comment]
When you say it isn't working, how do you know? Are you getting an error? Or are you just not getting the expected output?

**Comment by theDyingday** [comment]
I personally see this as a more viable option as when you're dealing with randomly selecting a value from an array your array starts from index 0 anyway. 
`public static String ChooseRandom(ArrayList<String> arr) {
        return arr.get((int) (Math.random() * arr.size()));
    }`

**Comment by PotatoCurry** [comment]
Thanks for your help @theDyingday, I receive this error when doing it both ways, so I don't think it's a problem with the code I mentioned previously.
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at Yibot.Main.ChooseRandom(Main.java:78)
	at Yibot.Main.Respond(Main.java:72)
	at Yibot.Main.InitializeChat(Main.java:55)
	at Yibot.Main.main(Main.java:18)
```
This seems to imply the `ArrayList` is empty, but at least to me, it looks like I added the values earlier.

**Comment by PotatoCurry** [comment]
Nevermind, I was adding responses to the wrong `Arraylist`, which explains why it returned an error claiming it was empty.
